version: '2.1'
services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:5.0.0
    ports:
      - "9080:9080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=H2
    #command: -b 0.0.0.0 -Djboss.http.port=8081 -Dkeycloak.migration.action=export -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/tmp/keycloak/test
    command: -b 0.0.0.0 -Djboss.http.port=9080 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/tmp/keycloak/test -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    volumes:
      - ./setup:/tmp/keycloak/test/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://keycloak:9080"]
      interval: 30s
      timeout: 10s
      retries: 10  
  tcp_client:
    build: client
    depends_on:
       keycloak:
           condition: service_healthy
    # command: sh -c './code/wait.sh keycloak:9080 -- echo READY && mvnw'
    # volumes:
     # - .:/code





    # command: sh -c 'sleep 2 && node ./code/client.js'

       # command: sh -c './code/wait.sh tcp_server:6969 -- echo working'
